In [1]:
import numpy as np

In [2]:
path = '../Kitti/raw/training/velodyne/000000.bin'
points = np.fromfile(path)
points = points.reshape((-1, 4))
print(points)

[[ 1.75532468e-013  5.24936998e-315  9.12696172e-011  5.24936998e-315]
 [ 3.29589896e-005  5.30266854e-315  3.40938657e-008  5.24936998e-315]
 [ 1.23023967e-007  2.21189212e-011  3.35693416e-007  1.34110483e-008]
 ...
 [-9.45000202e-002  2.21252549e-006 -8.74999912e-002  1.75476157e-006]
 [-7.95000345e-002  1.44958608e-006 -7.80000241e-002  8.96454253e-007]
 [-7.05000312e-002  4.27246323e-006 -1.12000004e-001  1.59090418e-314]]


In [3]:
calib = {}
with open('../Kitti/raw/training/calib/000000.txt') as inp:
    for line in inp.readlines():
        if ':' in line:
            key, value = line.split(':', 1)
            calib[key] = np.array([float(x) for x in value.split()])
P2_rect = calib['P2'].reshape(3, 4)

In [12]:
points_1 = points[:, 0:3]
points_1 = np.transpose(points_1)
points_1 = np.vstack((points_1, np.ones((points_1.shape[-1]))))
points_2D = P2_rect.dot(points_1)
points_2D = points_2D / points_2D[2]
points_2D = np.rint(points_2D).astype(int)
print(points_2D)

[[9187 9191 9186 ...  896  788  670]
 [ -69  -69  -69 ...  196  198  192]
 [   1    1    1 ...    1    1    1]]


In [16]:
depth = np.zeros((1224, 370))
for i in range(points_2D.shape[1]):
    x = points_2D[0, i]
    y = points_2D[1, i]
    if -1 < x < 1224 and -1 < y < 370:
        depth[x, y] = np.sqrt(np.square(points[i, 0:3]).sum())
        print(x, y)
        print(np.sqrt(np.square(points[i, 0:3]).sum()))
print(depth)

722 180
1.337844842568974
1217 180
21.644592479434632
1202 180
25.615995971049365
1214 180
44.42749221983225
1202 180
56.77158226770925
1208 180
96.24103267438043
1216 180
133.0335577916128
1207 180
160.16111545067764
1191 180
218.16737470089294
1198 181
502.9414546826399
1216 181
12173.213082876991
834 181
164680.31870866587
1204 181
130284.0744483026
947 181
271005.6992490215
906 181
316692.51223450876
926 181
435704.52423376846
874 181
591615.6134288117
1167 181
305873420152.09973
1047 181
694308903.1520597
1111 181
485659555.667464
1004 181
590915613.4302843
1183 181
605377347.534973
1001 181
1003147761.8467588
612 181
205071726601.72958
1000 181
448249769264.8024
1129 181
18582693.72300539
1064 181
39521954.59477332
876 181
35893304.86655249
795 181
94902284.115867
1140 181
30813393.001820028
727 181
30604014.346924037
775 181
30900333.47859232
882 181
32634850.417638313
804 181
38197723.93390188
1220 181
20435467.75164619
604 181
39409705.92211293
641 181
37633352.25464687
626 18