In [1]:
import torch
import cv2
from fixed_polygon_iou_loss import *
from matplotlib import pyplot as plt
import numpy as np

In [3]:
polygon = torch.tensor([[[124.35, 46.53], [253.35, 21.31], [333.31, 214.3], [134.31, 11.3]], [[124.35, 46.53], [253.35, 21.31], [333.31, 214.3], [134.31, 11.3]]], dtype=torch.float)
polygon = batch_clockify(polygon)
polygon2 = torch.tensor([[[124.35, 46.53], [253.35, 21.31], [333.31, 214.3], [134.31, 11.3], [134.31, 11.3], [134.31, 11.3]], [[124.35, 46.53], [253.35, 21.31], [333.31, 214.3], [134.31, 11.3], [134.31, 11.3], [134.31, 11.3]]], dtype=torch.float)
polygon3 = torch.tensor([[[108.35, 53.53], [203.35, 234.31], [34.31, 24.3], [666.31, 126.3]], [[108.35, 53.53], [203.35, 234.31], [34.31, 24.3], [666.31, 126.3]]], dtype=torch.float)
polygon2 = batch_clockify(polygon2)
print(batch_poly_area(polygon))
print(batch_poly_area(polygon2))
print(batch_poly_diou_loss(polygon, polygon3))
print(c_poly_diou_loss(polygon[0], polygon3[0]))

tensor([15602.8906, 15602.8906])
tensor([15602.8906, 15602.8906])
tensor([0.8116, 0.8116], dtype=torch.float64)
tensor(0.8116)
